#plugin:
#    base_dir: C:\Users\cmx\.p
#    plugin_cache: plugin_cache.cache
#    remote_resource: D:\code\plugins\plugin-core\resource.all
spring:
    profiles:
        active: dev,plugin,web
    redis:
        database: 0
        host: 192.168.85.129
        port: 6379
        password: 123456
        pool:
            max-active: 10
            max-wait: 50000
            max-idle: 8
            min-idle: 0
        timeout: 60000
redis:
    remote-key: remote_cache
    remote-expire: 86400000
server:
    port: 8080
